# -*- coding: utf-8 -*-
"""Turunan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KdfB6s1DEsYMm3CKguHm4A3YKQkIjAkP
"""



import numpy as np
from scipy.linalg import lu_factor, lu_solve

# Memasukkan ukuran matriks dari pengguna
n = int(input("Masukkan jumlah variabel/ukuran matriks: "))

# Memasukkan matriks koefisien dari pengguna
print("Masukkan matriks koefisien:")
matrix = np.zeros((n, n))
for i in range(n):
    matrix[i] = list(map(float, input().split()))

# Memasukkan vektor hasil dari pengguna
print("Masukkan vektor hasil:")
vector = np.array(list(map(float, input().split())))

try:
    # Melakukan faktorisasi LU
    lu, piv = lu_factor(matrix)

    # Menyelesaikan sistem persamaan linear dengan metode determinasi LU
    hasil = lu_solve((lu, piv), vector)

    print("Solusi dari sistem persamaan linear adalah:")
    for i in range(n):
        print(f"x{i+1} = {hasil[i]}")
except Exception as e:
    print("Terjadi kesalahan:", e)